#!/bin/bash
#
#
# Common bash components

################
### DEFAULTS ###
################

# COMMAND_FILE - full path and file name to where the commands required to be run,
# based on a configuration file, are stored. Commands are generated via Python as
# it is much easier to handle YAML files within Python. Changing the default is 
# useful for testing.
# Default: /tmp/ros-service-commands
COMMAND_FILE="/tmp/ros-service-commands"

# CONFIG_FILE - full path to a configuration file. The default path is based on the 
# current user. Changing the default is  useful for testing.
# Default: /home/<current-user>/.qcr/ros-service-config.yml
CONFIG_FILE="home/$USER/.qcr/ros-service-config.yml"

# CONFIG_FILE_SYMLINK - the location of the symbolic link. The symbolic link
# points to the current configuration file in use. Changing the default is 
# useful for testing.
# Default: /opt/qcr/ros-service-config.yml
CONFIG_FILE_SYMLINK="/opt/qcr/ros-service-config.yml"

# DEFAULT_CONFIG_FILE - the location of the default config file. Changing the default
# is useful for testing.
# Default: /opt/qcr/ros-service-config_default.yml
DEFAULT_CONFIG_FILE="/opt/qcr/ros-service-config_default.yml"

# SERVICE_PATH - contains the path to where systemd service files are stored.
# Changing the default is useful for testing.
# Default: /etc/systemd/system/.
SERVICE_PATH="/etc/systemd/system/"

# SERVICE_PREFIX - contains a string prefixed to the generated service files.
# Default: ros
SERVICE_PREFIX="ros"

# SERVICE_USER - contains a string appended to the generated service files prior to the '.service' file extension.
# Default: current user
SERVICE_USER=$USER


# Screen Colour Helpers
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
NORMAL=$(tput sgr0)


#################
### FUNCTIONS ###
#################